server:
  port: 8081
  servlet:
    context-path: /api/v1/private/service/one

spring:
  application:
    name: service-one
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Test
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: test-cli
      principal-attribute: preferred_username


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

keycloak:
  base-url: http://localhost:8080
  realm: Test
  client:
    intra-service:
      client-id: confidential-cli
      client-secret: QgIRkDxjp375yqFaoZoua1VOdPECXIWe
      grant-type: client_credentials
